import Head from 'next/head'
import { useRouter } from 'next/router'
import { useAuthState } from 'react-firebase-hooks/auth'
import { useCollection } from 'react-firebase-hooks/firestore'
import Loading from '../components/Loading'
import Sidebar from '../components/Sidebar'
import { auth, db } from '../firebase'

export default function Home() {
  const router = useRouter()
  const [user] = useAuthState(auth)
  const userChatRef = db.collection('chats').where('users','array-contains',user.email)
  const [chatSnapshot,loading] = useCollection(userChatRef)

  if(!loading && chatSnapshot){
    router.push(`/chat/${chatSnapshot.docs[0].id}`)
  }
  
  return (
    <>
    {loading?<Loading/>:
      (<div>
        <Head>
        <title>WhatsappWeb Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Sidebar/>
      </div>
      )
    }
    </>
  )
}
